# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./FPL.h
SOURCES += ./FPL.cpp \
    ./main.cpp
FORMS += ./FPL.ui
RESOURCES += FPL.qrc
